# Generated by Django 3.2.10 on 2024-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_auto_20240215_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
