# Generated by Django 4.2.10 on 2024-03-20 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gymapp", "0004_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="schedule",
        ),
        migrations.AddField(
            model_name="booking",
            name="newClass",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="gymapp.class",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="end_time",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="class",
            name="start_time",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="booking",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
