# Generated by Django 4.2.10 on 2024-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymapp", "0005_remove_booking_schedule_booking_newclass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
