# Generated by Django 4.2.10 on 2024-03-22 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gymapp", "0006_alter_class_end_time_alter_class_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
