# Generated by Django 4.2.10 on 2024-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymapp", "0007_alter_attendance_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="location",
        ),
        migrations.AddField(
            model_name="attendance",
            name="branch",
            field=models.CharField(default="Dokki", max_length=255),
        ),
    ]
